-- Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS users
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    user_name VARCHAR(255),
    birthday DATE NOT NULL
);

-- Создание таблицы фильмов
CREATE TABLE IF NOT EXISTS films
(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa_id INTEGER REFERENCES mpa_ratings(mpa_id)
);

-- Создание таблицы жанров
CREATE TABLE IF NOT EXISTS genres
(
    genre_id INTEGER PRIMARY KEY,
    genre_name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- Создание таблицы рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa_ratings
(
    mpa_id INTEGER PRIMARY KEY,
    mpa_name VARCHAR(10) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- Добавление связи фильмов с рейтингами MPA
ALTER TABLE films ADD COLUMN IF NOT EXISTS mpa_id INTEGER REFERENCES mpa_ratings(mpa_id);

-- Создание таблицы связи фильмов и жанров
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id INTEGER NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genres(genre_id),
    PRIMARY KEY (film_id, genre_id)
);

-- Создание таблицы лайков
CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

-- Создание таблицы друзей
CREATE TABLE IF NOT EXISTS friends
(
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    friend_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'UNCONFIRMED',
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT no_self_friendship CHECK (user_id <> friend_id)
);